export const ADD_TO_PORTFOLIO = 'ADD_TO_PORTFOLIO';
export const REMOVE_FROM_PORTFOLIO = 'REMOVE_FROM_PORTFOLIO';
export const SET_PORFOLIO = 'SET_PORFOLIO';
export const RANDOMIZE_PORTFOLIO = 'RANDOMIZE_PORTFOLIO';
